In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
grid = np.array([[0, 0, 0, 0],
                 [0, 0, 0, 0],
                 [0, 0, 0, 0],
                 [0, 0, 0, 10]], dtype = np.float32)

In [28]:
min(2, 3)

2

In [29]:
grid[(0, 3)]

0.0

In [34]:
grid1 = grid.copy()
numIter = 100
gamma = 0.99
# actionList = ['left', 'right', 'down', 'up']
actionList = ['right', 'down']
actionToIndex = {'left':(0, -1), 'right':(0, 1), 'down':(1, 0), 'up':(-1, 0)}

def takeAction(i, j, action):
    df = actionToIndex[action]
    nState = (i + df[0], j + df[1])
    if(nState[0] >=0 and nState[0] < 4 and nState[1] >= 0 and nState[1]<4):
        return nState
    return None

def getReward(grid, i, j, action):
    reward = 0
    for a in actionList:
        nState = takeAction(i, j, a)
        if nState is None:
            continue
        if(a == action):
            reward += 0.6*grid[nState]
        else:
            reward += 0.2*grid[nState]
            
    reward += 0.2*grid[i, j]
            
    return reward - 1
        

for _ in range(numIter):
    for i in range(4):
        for j in range(4):
            if(i == 3 and j == 3):
                continue
            maxReward = -1000
            for action in actionList:
                reward = getReward(grid1, i, j, action)
                maxReward = max(reward, maxReward)
            
            grid1[i, j] = maxReward
    
    print(grid1)
    print("\n")

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  5.]
 [-1. -1.  5. 10.]]


[[-2.  -2.  -2.  -1.4]
 [-2.  -2.  -2.   1.8]
 [-2.  -2.   2.8  6. ]
 [-1.4  1.8  6.  10. ]]


[[-3.         -3.         -2.6399999  -0.20000002]
 [-3.         -3.          0.64        2.96      ]
 [-2.6399999   0.64        4.36        6.2       ]
 [-0.20000002  2.96        6.2        10.        ]]


[[-4.        -3.784     -1.184      0.736    ]
 [-3.784     -1.088      2.336      3.3119998]
 [-1.184      2.336      4.832      6.24     ]
 [ 0.736      3.3119998  6.24      10.       ]]


[[-4.8272     -2.6464      0.31199998  1.1343999 ]
 [-2.6464      0.65119994  3.0287998   3.4063997 ]
 [ 0.31199998  3.0287998   4.9584      6.248     ]
 [ 1.1343999   3.4063997   6.248      10.        ]]


[[-4.08256   -1.0761601  1.1065599  1.2707198]
 [-1.0761601  1.5532798  3.2620797  3.43008  ]
 [ 1.1065599  3.2620797  4.99008    6.2496   ]
 [ 1.2707198  3.43008    6.2496    10.       ]]


[[-2.6774402  -0.06195218  1.4

In [33]:
grid1 = grid.copy()
numIter = 100
gamma = 0.99
# actionList = ['left', 'right', 'down', 'up']
actionList = ['right', 'down']
actionToIndex = {'left':(0, -1), 'right':(0, 1), 'down':(1, 0), 'up':(-1, 0)}

def takeAction(i, j, action):
    df = actionToIndex[action]
    nState = (i + df[0], j + df[1])
    if(nState[0] >=0 and nState[0] < 4 and nState[1] >= 0 and nState[1]<4):
        return nState
    return None

def getReward(grid, i, j, action):
    reward = 0
    for a in actionList:
        nState = takeAction(i, j, a)
        if nState is None:
            continue
        if(a == action):
            reward += 0.8*grid[nState]
        else:
            reward += 0.2*grid[nState]
            
    return reward 
        

for _ in range(numIter):
    for i in range(4):
        for j in range(4):
            if(i == 3 and j == 3):
                continue
            maxReward = -1000
            for action in actionList:
                reward = getReward(grid1, i, j, action)
                maxReward = max(reward, maxReward)
            
            grid1[i, j] = maxReward
    
    print(grid1)
    print("\n")

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  8.]
 [ 0.  0.  8. 10.]]


[[ 0.   0.   0.   0. ]
 [ 0.   0.   0.   6.4]
 [ 0.   0.   8.   8. ]
 [ 0.   6.4  8.  10. ]]


[[ 0.    0.    0.    5.12]
 [ 0.    0.    7.68  6.4 ]
 [ 0.    7.68  8.    8.  ]
 [ 5.12  6.4   8.   10.  ]]


[[ 0.         0.         7.1679997  5.12     ]
 [ 0.         7.68       7.68       6.4      ]
 [ 7.1679997  7.68       8.         8.       ]
 [ 5.12       6.4        8.        10.       ]]


[[ 0.         7.5776     7.1679997  5.12     ]
 [ 7.5776     7.68       7.68       6.4      ]
 [ 7.1679997  7.68       8.         8.       ]
 [ 5.12       6.4        8.        10.       ]]


[[ 7.5776     7.5776     7.1679997  5.12     ]
 [ 7.5776     7.68       7.68       6.4      ]
 [ 7.1679997  7.68       8.         8.       ]
 [ 5.12       6.4        8.        10.       ]]


[[ 7.5776     7.5776     7.1679997  5.12     ]
 [ 7.5776     7.68       7.68       6.4      ]
 [ 7.1679997  7.68       8.         8.       ]
 