In [20]:
import numpy as np
import pickle
import os
import pandas as pd

In [21]:
os.listdir()

['time',
 'lab2.py',
 '.~lock.traffic_details.csv#',
 'lab2.pdf',
 '.ipynb_checkpoints',
 'vehicle',
 'traffic_details.csv',
 'road',
 'lab2-A*.ipynb']

In [22]:
time = np.array(np.load('time', encoding = 'latin1')).astype(np.float)/60
display(time.shape)
print("time =",time[0:3,:])

(100, 1)

time = [[ 0.01749436]
 [ 0.03836497]
 [ 0.04407601]]


In [23]:
vehicle = np.array(np.load('vehicle'))
display(vehicle.shape)
print("vehicle = ",vehicle[0:3,:])

(100, 5)

vehicle =  [[1 0 5 3 7]
 [7 8 7 8 7]
 [3 7 0 1 9]]


In [24]:
road = np.array(np.load('road')).astype(np.float)
print(road.shape)
print( "road = ",road)

(10, 10)
road =  [[ 0.  3.  6.  0.  0.  8.  0.  0.  0.  0.]
 [ 8.  0.  0.  0.  0.  0.  0.  0.  9.  2.]
 [ 0.  7.  0.  0.  0.  0.  8.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  4.  7.  0.]
 [ 0.  9.  0.  0.  0.  0.  3.  0.  0.  0.]
 [ 5.  0.  2.  9.  0.  0.  0.  0.  0.  0.]
 [ 7.  2.  0.  0.  6.  0.  0.  0.  0.  0.]
 [ 6.  0.  0.  0.  0.  9.  0.  0.  5.  0.]
 [ 0.  3.  2.  0.  0.  0.  0.  1.  0.  0.]
 [ 3.  0.  0.  0.  0.  0.  0.  5.  0.  0.]]


In [25]:
def calcSpeed(x):
    return np.exp(.5*x)/(1 + np.exp(0.5*x)) + 15/(1 + np.exp(0.5*x))

In [26]:
class mainListItem:
    def __init__(self, vehicle_no, start_time, source, departure):
        self.vehicle_no = vehicle_no
        self.start_time =start_time
        self.source = source
        self.destination = departure
    def printObject(self):
        print(self.vehicle_no, self.start_time, self.source, self.destination);

In [27]:
time[0, 0]

0.017494358116171692

In [28]:
mainList = []
for i in range(0, time.shape[0]):
    src = vehicle[i,0]
    dest = vehicle[i,1]
    mainList.append(mainListItem(i, time[i, 0], src, dest))

In [29]:
mainList.sort(key = lambda x:x.start_time, reverse = False)

In [30]:
class RoadItem:
    def __init__(self, vehicle_no, arrival_time, departure_time):
        self.vehicle_no = vehicle_no
        self.arrival_time = arrival_time
        self.departure_time = departure_time
    def printObject(self):
        print(self.vehicle_no, self.arrival_time, self.departure_time)

In [31]:
import sys
INT_MAX = sys.maxsize
roadList = [[[] for j in range(10)] for k in range(10)]
# roadList.append(road[0,:].tolist)
# roadList[0]
print(len(roadList), len(roadList[0]), len(roadList[0][0]))

10 10 0


In [32]:
min(mainList, key = lambda x:x.start_time).start_time

0.017494358116171692

In [33]:
print(np.array(road))

[[ 0.  3.  6.  0.  0.  8.  0.  0.  0.  0.]
 [ 8.  0.  0.  0.  0.  0.  0.  0.  9.  2.]
 [ 0.  7.  0.  0.  0.  0.  8.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  4.  7.  0.]
 [ 0.  9.  0.  0.  0.  0.  3.  0.  0.  0.]
 [ 5.  0.  2.  9.  0.  0.  0.  0.  0.  0.]
 [ 7.  2.  0.  0.  6.  0.  0.  0.  0.  0.]
 [ 6.  0.  0.  0.  0.  9.  0.  0.  5.  0.]
 [ 0.  3.  2.  0.  0.  0.  0.  1.  0.  0.]
 [ 3.  0.  0.  0.  0.  0.  0.  5.  0.  0.]]


In [34]:
output = np.zeros(vehicle.shape)
output.shape

(100, 5)

In [35]:
def timeTaknOnCurrRoad(vehicle_no, destination, length, currRoadCarList, start_time):
    timeTaken = 0;
    carAhead = 0;
    sz = len(currRoadCarList)
    mainList.sort(key = lambda x:x.start_time, reverse = True)
    tot = 0
    for i in range(len(currRoadCarList)):
        if(vehicle_no == 0):
            print("DepartureTime = ", currRoadCarList[sz - 1].departure_time)
        if(start_time < currRoadCarList[sz - 1].departure_time):
            tot = tot + 1
            sz-=1
        else:
            break;
    ind = 0
    last_time = start_time
    if(vehicle_no == 0):
        print("lenCurrRoad = ",len(currRoadCarList), "tot = ", tot, "length = ", length, "Speed =",calcSpeed(0))
    while(tot>0 and length > 0):
        currTravel = calcSpeed(tot) * (currRoadCarList[ind].departure_time - last_time)
        if(currTravel >= length):
            if(currObj.vehicle_no == 0):
                print("decreasing1", tot, length, calcSpeed(tot))
            length = length - currTravel
            timeTaken = timeTaken + currRoadCarList[ind].departure_time - last_time
            last_time = currRoadCarList[ind].departure_time
        else:
            if(currObj.vehicle_no == 0):
                print("decreasing2", tot, length)
            length = 0
            timeTaken = timeTaken + (length/calcSpeed(tot))
        if(currObj.vehicle_no == 0):
            print("decreasing", tot, len)
        tot-=1;
        ind+=1;
    if(length>0.0):
        if(vehicle_no == 0):
            print("Lenght not zero", length)
        timeTaken += length/calcSpeed(0)
    return timeTaken

In [36]:
while len(mainList)!=0:
    mainList.sort(key = lambda x:x.start_time, reverse = True)
#     print(mainList)
    currObj = mainList.pop()
    if(currObj.vehicle_no == 0):
        print("CurrObj = ")
        currObj.printObject()
    if output[currObj.vehicle_no][0] == 4:
        continue
    currRoadCarList = roadList[currObj.source][currObj.destination]     #Type: RoadItem
    timeTaken = timeTaknOnCurrRoad(currObj.vehicle_no,
                                   currObj.destination, 
                                   road[currObj.source, currObj.destination], 
                                   currRoadCarList,
                                  currObj.start_time)
    if(currObj.vehicle_no == 0):
            print("timeTaken = ", timeTaken)
    roadList[currObj.source][currObj.destination].append(RoadItem(currObj.vehicle_no,
                                                                  currObj.start_time, 
                                                                  currObj.start_time + timeTaken))
    output[currObj.vehicle_no][0] = output[currObj.vehicle_no][0].astype(np.int)+1
    ind1 = output[currObj.vehicle_no][0].astype(np.int)
#     print(ind1)
    output[currObj.vehicle_no][ind1] = currObj.start_time + timeTaken
#     print(timeTaken, "startTime = ", currObj.start_time)
    if output[currObj.vehicle_no][0] != 4:
        st = currObj.start_time + timeTaken,
#         print("appending", st)
        mainList.append(mainListItem(currObj.vehicle_no,
                                st[0],
                                currObj.destination,
                                vehicle[currObj.vehicle_no][output[currObj.vehicle_no][0].astype(np.int) + 1]))
#     mainListItem(currObj.vehicle_no, 
# currObj.start_time,
# currObj.source,
# currObj.destination)

CurrObj = 
0 0.0174943581162 1 0
lenCurrRoad =  0 tot =  0 length =  8.0 Speed = 8.0
Lenght not zero 8.0
timeTaken =  1.0
CurrObj = 
0 1.01749435812 0 5
DepartureTime =  1.01645490884
lenCurrRoad =  12 tot =  0 length =  8.0 Speed = 8.0
Lenght not zero 8.0
timeTaken =  1.0
CurrObj = 
0 2.01749435812 5 3
DepartureTime =  2.55932086536
DepartureTime =  1.35214020749
lenCurrRoad =  13 tot =  1 length =  9.0 Speed = 8.0
decreasing2 1 9.0
decreasing 1 <built-in function len>
timeTaken =  0.0
CurrObj = 
0 2.01749435812 3 7
DepartureTime =  1.88330921794
lenCurrRoad =  9 tot =  0 length =  4.0 Speed = 8.0
Lenght not zero 4.0
timeTaken =  0.5


In [37]:
print(output)

[[ 4.          1.01749436  2.01749436  2.01749436  2.51749436]
 [ 4.          0.66336497  0.78836497  1.41336497  1.41336497]
 [ 4.          0.54407601  0.54407601  0.91907601  0.91907601]
 [ 4.          0.92046561  1.92046561  1.92046561  2.92046561]
 [ 4.          0.1845514   0.9345514   1.3095514   1.3095514 ]
 [ 4.          0.44651686  1.19651686  1.19651686  1.44651686]
 [ 4.          0.07819658  0.07819658  0.20319658  0.20319658]
 [ 4.          0.34285789  0.96785789  2.09285789  3.21785789]
 [ 4.          0.98469408  0.98469408  2.10969408  2.23469408]
 [ 4.          0.35984826  1.48484826  1.60984826  1.60984826]
 [ 4.          0.74311277  0.74311277  1.86811277  2.11811277]
 [ 4.          1.24884028  1.24884028  2.12384028  2.12384028]
 [ 4.          1.2505523   1.2505523   1.3755523   1.3755523 ]
 [ 4.          0.13035967  0.50535967  0.75535967  1.38035967]
 [ 4.          0.13086729  0.13086729  0.75586729  0.75586729]
 [ 4.          0.14590514  0.14590514  0.89590514  1.77

In [38]:
mainList[len(mainList) - 1].printObject()

IndexError: list index out of range

In [ ]:
time

In [ ]:
road

In [ ]:
temp = [[[],[]],[[],[]]]
print(temp)

In [ ]:
temp[1][0].append(2)
print(temp)